---
- hosts: all
  become: yes
  tasks:
    - name: update system
      apt: upgrade=dist force_apt_get=yes
    - name: installing snapd
      apt:
        pkg:
          - snapd
    - name: installing nextcloud
      command: snap install nextcloud 
    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: 80
        proto: tcp
    - name: Allow all access to tcp port 443
      ufw:
        rule: allow
        port: 443
        proto: tcp
   



